sylius_ui:
  events:
    sylius.admin.channel.form.second_column_content:
      blocks:
        avis_verifies:
          template: '@IkuzoSyliusSendinbluePlugin/Channel/_form.html.twig'
          priority: 5
